version: 0.0
os: linux
files:
  - source: /
    destination: /app/
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user